# -*- coding: utf-8 -*-
"""YoloV8_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvirRoC-wMz8KPsag7v8bBkcqqY4ibJO

Let's make sure that we have access to GPU.
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""Install YOLOv8 and other requirements.

"""

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()


import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install -U albumentations

!pip install --upgrade albumentations torch ultralytics

"""Uploding custom database from Robo-flow"""


!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="CTZk6ZGQchToQIGWDfRX")
project = rf.workspace("breathless").project("bottle-ewqkq")
version = project.version(8)
dataset = version.download("yolov8")

"""Training"""


# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=50 imgsz=800 plots=True


"""Downloadig trained model to local device."""

from google.colab import files

# Replace with the path to your best.pt or last.pt file
files.download('runs/detect/train/weights/best.pt')

"""Training end."""
